### ISSUE TITLE
sass 中的图片不能写相对路径？

### ISSUE THREAD

**Issue by nimojs** [fex-team/fis-parser-sass#27]
a.scss
```css
.p-avatar{
    background:url(../img/avatar.jpeg);
}
```

a.css
```css
.p-avatar{background:url(/img/avatar.jpeg)}
```
