### ISSUE TITLE
scss语法支持不全

### ISSUE THREAD

**Issue by GhostYee** [fex-team/fis-parser-sass#9]
### 以下代码会被输出,是否语法支持不全

``` scss
// input, select, textarea的基础样式
// 边框，padding
%simple-form-basic{
  border: 1px solid $gray;
  padding: 4px;
  vertical-align: middle;
  &:focus{
    outline: 0 none;
  }
}
```

// 输入框

``` scss
@mixin simple-text($borderColorFocus: #52a8ec){
  @extend %simple-form-basic;
  height: 18px;

  @include transition(border linear 0.2s, box-shadow linear 0.2s);
  @include box-shadow(inset 0 1px 3px rgba(0, 0, 0, 0.1));

  &:focus{
    border-color: rgba($borderColorFocus, 0.8);
    @include box-shadow(inset 0 1px 3px rgba(0, 0, 0, 0.1), 0 0 8px rgba($borderColorFocus, 0.6));
  }  
}
%simple-text{
  @include simple-text;
}

// textarea
@mixin simple-textarea($borderColorFocus:#52a8ec, $width:500px, $height:80px){
  @include simple-text($borderColorFocus);
  height: $height;
  width: $width;
  vertical-align: top;
}
%simple-textarea{
  @include simple-textarea;
}

// select
%simple-select{
  @extend %simple-form-basic;

  // select lte ie7
  // ie6,7 不支持select的padding
  @if $lte7 {
      *margin-top:5px;
      *margin-bottom:5px;
      *vertical-align:top;
  }
}
```
# 

``` css
%simple-text, %simple-textarea, %simple-select {
  border: 1px solid #ccc;
  padding: 4px;
  vertical-align: middle; }
  %simple-form-basic:focus {
    outline: 0 none; }
```
